### ISSUE TITLE
Would you be open to me copying this over to eslint-plugin-canonical?

### ISSUE THREAD

**Issue by gajus** [christianvuerings/eslint-plugin-no-re-export#1]
https://github.com/gajus/eslint-plugin-canonical

With proper license attribution, of course.

I try to avoid single-rule packages as they tend to get abandoned.

Keeping it all in one repository, with conventions and tests that others can contribute to, ensures better long term sustainability.

**Comment by gajus** [comment]
For context, I already have related rules, such as https://github.com/gajus/eslint-plugin-canonical#no-barrel-import. But don't have one that prevents re-exports.

**Comment by christianvuerings** [comment]
@gajus yes! Feel free to add as is - thanks for porting it over

**Comment by gajus** [comment]
Thank you
